<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="3" total="6" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="24371" started-at="2022-09-07T17:52:59 IST" finished-at="2022-09-07T17:53:23 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="24371" started-at="2022-09-07T17:52:59 IST" finished-at="2022-09-07T17:53:23 IST">
      <class name="com.demoQA.tests.Datepicker_Test">
        <test-method status="PASS" signature="beforetest()[pri:0, instance:com.demoQA.tests.Datepicker_Test@74ad1f1f]" name="beforetest" is-config="true" duration-ms="13625" started-at="2022-09-07T17:52:59 IST" finished-at="2022-09-07T17:53:12 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforetest -->
        <test-method status="PASS" signature="beforeclass()[pri:0, instance:com.demoQA.tests.Datepicker_Test@74ad1f1f]" name="beforeclass" is-config="true" duration-ms="425" started-at="2022-09-07T17:53:12 IST" finished-at="2022-09-07T17:53:13 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeclass -->
        <test-method status="FAIL" signature="verifyDateByPrevNextBtn(int, int, int)[pri:0, instance:com.demoQA.tests.Datepicker_Test@74ad1f1f]" name="verifyDateByPrevNextBtn" duration-ms="2803" started-at="2022-09-07T17:53:14 IST" data-provider="dp2" finished-at="2022-09-07T17:53:17 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[2020]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[8]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[12]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [08/15/2015] but found [08/12/2020]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [08/15/2015] but found [08/12/2020]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.demoQA.tests.Datepicker_Test.verifyDateByPrevNextBtn(Datepicker_Test.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyDateByPrevNextBtn -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.demoQA.tests.Datepicker_Test@74ad1f1f]" name="afterMethod" is-config="true" duration-ms="472" started-at="2022-09-07T17:53:17 IST" finished-at="2022-09-07T17:53:18 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyDateByPrevNextBtn status=FAILURE method=Datepicker_Test.verifyDateByPrevNextBtn(int, int, int)[pri:0, instance:com.demoQA.tests.Datepicker_Test@74ad1f1f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="verifyDateByPrevNextBtn(int, int, int)[pri:0, instance:com.demoQA.tests.Datepicker_Test@74ad1f1f]" name="verifyDateByPrevNextBtn" duration-ms="2411" started-at="2022-09-07T17:53:18 IST" data-provider="dp2" finished-at="2022-09-07T17:53:20 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[2022]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[9]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[13]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [08/15/2015] but found [09/13/2022]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [08/15/2015] but found [09/13/2022]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.demoQA.tests.Datepicker_Test.verifyDateByPrevNextBtn(Datepicker_Test.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyDateByPrevNextBtn -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.demoQA.tests.Datepicker_Test@74ad1f1f]" name="afterMethod" is-config="true" duration-ms="276" started-at="2022-09-07T17:53:20 IST" finished-at="2022-09-07T17:53:20 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyDateByPrevNextBtn status=FAILURE method=Datepicker_Test.verifyDateByPrevNextBtn(int, int, int)[pri:0, instance:com.demoQA.tests.Datepicker_Test@74ad1f1f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="verifyDateByPrevNextBtn(int, int, int)[pri:0, instance:com.demoQA.tests.Datepicker_Test@74ad1f1f]" name="verifyDateByPrevNextBtn" duration-ms="1474" started-at="2022-09-07T17:53:20 IST" data-provider="dp2" finished-at="2022-09-07T17:53:22 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[2023]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[14]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [08/15/2015] but found [10/14/2023]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [08/15/2015] but found [10/14/2023]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.demoQA.tests.Datepicker_Test.verifyDateByPrevNextBtn(Datepicker_Test.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyDateByPrevNextBtn -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.demoQA.tests.Datepicker_Test@74ad1f1f]" name="afterMethod" is-config="true" duration-ms="260" started-at="2022-09-07T17:53:22 IST" finished-at="2022-09-07T17:53:22 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyDateByPrevNextBtn status=FAILURE method=Datepicker_Test.verifyDateByPrevNextBtn(int, int, int)[pri:0, instance:com.demoQA.tests.Datepicker_Test@74ad1f1f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="after()[pri:0, instance:com.demoQA.tests.Datepicker_Test@74ad1f1f]" name="after" is-config="true" duration-ms="681" started-at="2022-09-07T17:53:22 IST" finished-at="2022-09-07T17:53:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- after -->
      </class> <!-- com.demoQA.tests.Datepicker_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
